//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gosocket.Dian.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gosocket.Dian.Common.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptación expresa de la Factura  Electrónica.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        public static string alertType {
            get {
                return ResourceManager.GetString("alertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string confirmType {
            get {
                return ResourceManager.GetString("confirmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea habilitar  la trasmisión de eventos al RADIAN como Facturador Electrónico?.
        /// </summary>
        public static string ElectronicInvoice_Confirm {
            get {
                return ResourceManager.GetString("ElectronicInvoice_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endoso Electronico.
        /// </summary>
        public static string Endoso {
            get {
                return ResourceManager.GetString("Endoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura Electronica.
        /// </summary>
        public static string Event_DocumentType {
            get {
                return ResourceManager.GetString("Event_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandato por documento.
        /// </summary>
        public static string Event_MandateType {
            get {
                return ResourceManager.GetString("Event_MandateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias del Evento.
        /// </summary>
        public static string Event_ReferenceTitle {
            get {
                return ResourceManager.GetString("Event_ReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Disponibilización para Negociaciación General.
        /// </summary>
        public static string Event_RequestType {
            get {
                return ResourceManager.GetString("Event_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación.
        /// </summary>
        public static string Event_Status_01 {
            get {
                return ResourceManager.GetString("Event_Status_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento validado por la DIAN.
        /// </summary>
        public static string Event_ValidationMessage {
            get {
                return ResourceManager.GetString("Event_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validaciones del Evento.
        /// </summary>
        public static string Event_ValidationTitle {
            get {
                return ResourceManager.GetString("Event_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea operar como Factor?.
        /// </summary>
        public static string Factor_Confirm {
            get {
                return ResourceManager.GetString("Factor_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro realizar la validación del participante a Registrar!!!.
        /// </summary>
        public static string FailedValidation {
            get {
                return ResourceManager.GetString("FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripción de Mandato Electrónico.
        /// </summary>
        public static string Mandato {
            get {
                return ResourceManager.GetString("Mandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe en el sistema!!!.
        /// </summary>
        public static string NonExistentParticipant {
            get {
                return ResourceManager.GetString("NonExistentParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante no cuenta con un software propio activo en el sistema.
        /// </summary>
        public static string ParticipantWithoutSoftware {
            get {
                return ResourceManager.GetString("ParticipantWithoutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constancia de Recibo de mercancia.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuse de Recibo de Factura Electrónica.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect.
        /// </summary>
        public static string redirectType {
            get {
                return ResourceManager.GetString("redirectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante ya se encuentra registrado en RADIAN.
        /// </summary>
        public static string RegisteredParticipant {
            get {
                return ResourceManager.GetString("RegisteredParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Primera Disponibilización.
        /// </summary>
        public static string SolicitudDisponibilizacion {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Disponibilización Posterior.
        /// </summary>
        public static string SolicitudDisponibilizacion1 {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante no es un proveedor tecnológico habilitado.
        /// </summary>
        public static string TechnologProviderDisabled {
            get {
                return ResourceManager.GetString("TechnologProviderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea habilitar la trasmisión de eventos al RADIAN como Proveedor Tecnológico?.
        /// </summary>
        public static string TechnologyProvider_Confirm {
            get {
                return ResourceManager.GetString("TechnologyProvider_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea operar como Sistema de Negociación?.
        /// </summary>
        public static string TradingSystem_Confirm {
            get {
                return ResourceManager.GetString("TradingSystem_Confirm", resourceCulture);
            }
        }
    }
}
