//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gosocket.Dian.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gosocket.Dian.Common.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptación expresa.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alert.
        /// </summary>
        public static string alertType {
            get {
                return ResourceManager.GetString("alertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos los archivos deben estar en estado &apos;Aceptado&apos; para poder cambiar el estado del participante..
        /// </summary>
        public static string AllSoftware {
            get {
                return ResourceManager.GetString("AllSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaptchaError.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa no asociada a representante legal..
        /// </summary>
        public static string CompanyDoesntAssociate {
            get {
                return ResourceManager.GetString("CompanyDoesntAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string confirmType {
            get {
                return ResourceManager.GetString("confirmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa no se encuentra habilitada..
        /// </summary>
        public static string DisabledCompany {
            get {
                return ResourceManager.GetString("DisabledCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para poder continuar, realiza el proceso de habilitación como Facturador Electrónico..
        /// </summary>
        public static string ElectronicBillerNoEnabled {
            get {
                return ResourceManager.GetString("ElectronicBillerNoEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea habilitar  la trasmisión de eventos al RADIAN como Facturador Electrónico?.
        /// </summary>
        public static string ElectronicInvoice_Confirm {
            get {
                return ResourceManager.GetString("ElectronicInvoice_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correo electrónico enviado correctamente.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endoso electrónico.
        /// </summary>
        public static string Endoso {
            get {
                return ResourceManager.GetString("Endoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factura Electrónica.
        /// </summary>
        public static string Event_DocumentType {
            get {
                return ResourceManager.GetString("Event_DocumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandato por documento.
        /// </summary>
        public static string Event_MandateType {
            get {
                return ResourceManager.GetString("Event_MandateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencias del evento.
        /// </summary>
        public static string Event_ReferenceTitle {
            get {
                return ResourceManager.GetString("Event_ReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Disponibilización para Negociaciación General.
        /// </summary>
        public static string Event_RequestType {
            get {
                return ResourceManager.GetString("Event_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificación.
        /// </summary>
        public static string Event_Status_01 {
            get {
                return ResourceManager.GetString("Event_Status_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documento validado por la DIAN.
        /// </summary>
        public static string Event_ValidationMessage {
            get {
                return ResourceManager.GetString("Event_ValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validaciones del evento.
        /// </summary>
        public static string Event_ValidationTitle {
            get {
                return ResourceManager.GetString("Event_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante ya tiene asociado el software asignado!!!.
        /// </summary>
        public static string ExistingSoftware {
            get {
                return ResourceManager.GetString("ExistingSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea operar como Factor?.
        /// </summary>
        public static string Factor_Confirm {
            get {
                return ResourceManager.GetString("Factor_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se logro realizar la validación del participante a Registrar!!!.
        /// </summary>
        public static string FailedValidation {
            get {
                return ResourceManager.GetString("FailedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no se encuentra activo.
        /// </summary>
        public static string InactiveUser {
            get {
                return ResourceManager.GetString("InactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falta algún dato del formulario.
        /// </summary>
        public static string IncompleteForm {
            get {
                return ResourceManager.GetString("IncompleteForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuyente tiene RUT en estado cancelado..
        /// </summary>
        public static string InvalidUserRut {
            get {
                return ResourceManager.GetString("InvalidUserRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña anterior no es correcta.
        /// </summary>
        public static string LastPasswordWrong {
            get {
                return ResourceManager.GetString("LastPasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscripción de Mandato Electrónico.
        /// </summary>
        public static string Mandato {
            get {
                return ResourceManager.GetString("Mandato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este modo de operación y documento electrónico carece de Set de Pruebas!!!.
        /// </summary>
        public static string ModeElectroniDocWithoutTestSet {
            get {
                return ResourceManager.GetString("ModeElectroniDocWithoutTestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelError.
        /// </summary>
        public static string ModelError {
            get {
                return ResourceManager.GetString("ModelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este modo de operación carece de Set de Pruebas!!!.
        /// </summary>
        public static string ModeWithoutTestSet {
            get {
                return ResourceManager.GetString("ModeWithoutTestSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no habilitado para el sistema!!!.
        /// </summary>
        public static string NonExistentParticipant {
            get {
                return ResourceManager.GetString("NonExistentParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiene otro proceso activo con software propio..
        /// </summary>
        public static string OnlyActiveProcess {
            get {
                return ResourceManager.GetString("OnlyActiveProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede registrar esta operación, tiene software en proceso!!..
        /// </summary>
        public static string OperationFailOtherInProcess {
            get {
                return ResourceManager.GetString("OperationFailOtherInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modo de operación adicionado correctamente.
        /// </summary>
        public static string OtherDocEleSuccesModeOperation {
            get {
                return ResourceManager.GetString("OtherDocEleSuccesModeOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea iniciar el proceso de habilitación para @docume?.
        /// </summary>
        public static string OthersElectronicDocumentsSelect_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelect_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea habilitar la trasmisión de &quot;Otros Documentos Electrónicos&quot; en el sistema como @Participante de otros documentos electrónicos?.
        /// </summary>
        public static string OthersElectronicDocumentsSelectOperationMode_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelectOperationMode_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Desea iniciar el proceso como @Participante de otros documentos electrónicos?.
        /// </summary>
        public static string OthersElectronicDocumentsSelectParticipante_Confirm {
            get {
                return ResourceManager.GetString("OthersElectronicDocumentsSelectParticipante_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos asociados correctamente..
        /// </summary>
        public static string OtherSuccessSoftware {
            get {
                return ResourceManager.GetString("OtherSuccessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante no cuenta con un software propio activo en el sistema.
        /// </summary>
        public static string ParticipantWithoutSoftware {
            get {
                return ResourceManager.GetString("ParticipantWithoutSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña debe contener: al menos (1) mayúscula, (1) minúscula, (1) dígito, (1) símbolo o carácter especial y debe ser de almenos 6 carácteres..
        /// </summary>
        public static string PasswordDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordError.
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las contraseñas no coinciden.
        /// </summary>
        public static string PasswordsArentEquals {
            get {
                return ResourceManager.GetString("PasswordsArentEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña actualizada correctamente.
        /// </summary>
        public static string PasswordUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://catalogo-vpfe.dian.gov.co/document/searchqr?documentkey={CUFE}.
        /// </summary>
        public static string RadianReportQRCode {
            get {
                return ResourceManager.GetString("RadianReportQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibo del bien y/o prestación del servicio.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuse de recibo de Factura Electrónica de Venta.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redirect.
        /// </summary>
        public static string redirectType {
            get {
                return ResourceManager.GetString("redirectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante ya se encuentra registrado en RADIAN.
        /// </summary>
        public static string RegisteredParticipant {
            get {
                return ResourceManager.GetString("RegisteredParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /document/searchqr?documentkey={CUFE}.
        /// </summary>
        public static string ReportQRCode {
            get {
                return ResourceManager.GetString("ReportQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El software es un campo obligatorio.
        /// </summary>
        public static string RequiredSoftware {
            get {
                return ResourceManager.GetString("RequiredSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No fue posible enviar el correo.
        /// </summary>
        public static string SendEmailFailed {
            get {
                return ResourceManager.GetString("SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor inicie sesión nuevamente e intente de nuevo.
        /// </summary>
        public static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Primera Disponibilización.
        /// </summary>
        public static string SolicitudDisponibilizacion {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Disponibilización Posterior.
        /// </summary>
        public static string SolicitudDisponibilizacion1 {
            get {
                return ResourceManager.GetString("SolicitudDisponibilizacion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datos actualizados correctamente..
        /// </summary>
        public static string SuccessSoftware {
            get {
                return ResourceManager.GetString("SuccessSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El participante no es un proveedor tecnológico habilitado.
        /// </summary>
        public static string TechnologProviderDisabled {
            get {
                return ResourceManager.GetString("TechnologProviderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea habilitar la trasmisión de eventos al RADIAN como Proveedor Tecnológico?.
        /// </summary>
        public static string TechnologyProvider_Confirm {
            get {
                return ResourceManager.GetString("TechnologyProvider_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los participantes &apos;En pruebas&apos; no se pueden cancelar..
        /// </summary>
        public static string TestNotRemove {
            get {
                return ResourceManager.GetString("TestNotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Está seguro que desea operar como Sistema de Negociación?.
        /// </summary>
        public static string TradingSystem_Confirm {
            get {
                return ResourceManager.GetString("TradingSystem_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario fue creado exitosamente.
        /// </summary>
        public static string UserCreatedSuccess {
            get {
                return ResourceManager.GetString("UserCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario no existe o no está registrado.
        /// </summary>
        public static string UserDoesntExist {
            get {
                return ResourceManager.GetString("UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserError.
        /// </summary>
        public static string UserError {
            get {
                return ResourceManager.GetString("UserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Usuario con el Tipo de Documento y Documento suministrados.
        /// </summary>
        public static string UserExistingDoc {
            get {
                return ResourceManager.GetString("UserExistingDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Usuario con el correo suministrado.
        /// </summary>
        public static string UserExistingEmail {
            get {
                return ResourceManager.GetString("UserExistingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no puedo ser asignado al role &apos;Usuario Facturador Gratuito&apos;.
        /// </summary>
        public static string UserRoleFail {
            get {
                return ResourceManager.GetString("UserRoleFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El usuario fue actualizado exitosamente.
        /// </summary>
        public static string UserUpdatedSuccess {
            get {
                return ResourceManager.GetString("UserUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Usuario no tiene una Empresa Asociada!.
        /// </summary>
        public static string UserWithOutCompany {
            get {
                return ResourceManager.GetString("UserWithOutCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El software de la operación tiene {0} clientes asociados..
        /// </summary>
        public static string WithCustomerList {
            get {
                return ResourceManager.GetString("WithCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el captcha.
        /// </summary>
        public static string WrongCaptcha {
            get {
                return ResourceManager.GetString("WrongCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña incorrecta.
        /// </summary>
        public static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
    }
}
