// <auto-generated />
namespace Gosocket.Dian.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewTablesMenuSubMenuPermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTablesMenuSubMenuPermission));
        
        string IMigrationMetadata.Id
        {
            get { return "202011171731077_NewTables-Menu-SubMenu-Permission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
